apiVersion: apps/v1
kind: Deployment
metadata:
  name: polling-app-prod
  labels:
    app: polling-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: polling-app
  template:
    metadata:
      labels:
        app: polling-app
    spec:
      containers:
      - name: polling-app
        image: polling-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: polling-app-prod-service
spec:
  selector:
    app: polling-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
